// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-mm3TgBXBg-51NlNBzpMnKXeSE-PfrpQ',
    appId: '1:907417611895:web:2dadfbfa86ca5f932f2072',
    messagingSenderId: '907417611895',
    projectId: 'dictionary-app-b0b43',
    authDomain: 'dictionary-app-b0b43.firebaseapp.com',
    storageBucket: 'dictionary-app-b0b43.appspot.com',
    measurementId: 'G-QKF0WGR2VD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXaShmcmm4XAE7BpAxr6ib6yjQLVbSxZc',
    appId: '1:907417611895:android:bf4121ffca85daa62f2072',
    messagingSenderId: '907417611895',
    projectId: 'dictionary-app-b0b43',
    storageBucket: 'dictionary-app-b0b43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJHOA5PiYqMl2PZl5PVKXnV7lCq4VUFFQ',
    appId: '1:907417611895:ios:b0e93283d922e3cd2f2072',
    messagingSenderId: '907417611895',
    projectId: 'dictionary-app-b0b43',
    storageBucket: 'dictionary-app-b0b43.appspot.com',
    iosClientId: '907417611895-3ul62uuvqp1gkm2tg22q8kirrdvfdbom.apps.googleusercontent.com',
    iosBundleId: 'com.example.dictionaryAppMatteo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJHOA5PiYqMl2PZl5PVKXnV7lCq4VUFFQ',
    appId: '1:907417611895:ios:3d4cacc4f540f0552f2072',
    messagingSenderId: '907417611895',
    projectId: 'dictionary-app-b0b43',
    storageBucket: 'dictionary-app-b0b43.appspot.com',
    iosClientId: '907417611895-03uckgh840dtemg5defasevo95r6ver6.apps.googleusercontent.com',
    iosBundleId: 'com.example.dictionaryAppMatteo.RunnerTests',
  );
}
